### ISSUE TITLE
YAML to use this platform

### ISSUE THREAD

**Issue by deej9999** [ldotlopez/ha-hnap-device#4]
Hi - do you have an example of the Yaml code I should put in the config file to get this integration to work? I want to add my dlink siren.

**Comment by ldotlopez** [comment]
You need to add this integration thru the web interface.

Go to integrations, add integration and search for "HNAP"

**Comment by deej9999** [comment]
Thanks - I already added the integration but how does it find devices? Does it search automatically?

**Comment by ldotlopez** [comment]
There is no automatic search.

You must add the device manually providing the camera IP, user (usually
admin) and password.

I recomend you to use the official (and deprecated) app My D-Link home to
do the initial configuration and then configure the HNAP integration. You
wouldn't need the app beyond the initial setup.
